---
title: "Mutational and CNA Signatures plots "
author: "Annie"
date: "2025-05-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}
##Loading packages

### diretorio da nova lib 24-06-2024
### ou diretório acessível em todos os nós
mylib <- "/data04/projects04/PatriciaPossik/pdx_la_sanger/lib/Rpackages/4.4.1"
libdir <- "/data04/tools/R/Rpackages/4.4.1"

### comando para efetivar a seleção de libPaths
.libPaths(c(mylib,libdir))
.libPaths()

#setting directory
setwd("~/pdx_la_sanger/results/mutational_signatures/")
### set CRAN Mirror https://cran-r.c3sl.ufpr.br/
options(repos = c("CRAN" = "https://cran-r.c3sl.ufpr.br/"))
# setting directory  
setwd("~/pdx_la_sanger/results/INCA_res")  
### set CRAN Mirror https://cran-r.c3sl.ufpr.br/  
options(repos = c("CRAN" = "https://cran-r.c3sl.ufpr.br/"))  

### Directory for the new library 24-06-2024  
libdir <- "/scr/R/Rpackages/4.4.1"  

##Dependencies for this project are recorded and managed with renv
## To setup your Rstudio environment you might need to run:
renv::restore()

here::i_am("scripts/02_Figure_S3b_c.R")
library(dplyr)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(scales)
library(ggpubr)
library(gridExtra)
library(data.table)
library(here)
library(renv)

```

#installing packages
```{r pressure, echo=FALSE}
install.packages("devtools")
install.packages("reticulate")

library(reticulate)
library(devtools)
if (!require("devtools")) install.packages("devtools")
devtools::install_github("AlexandrovLab/SigProfilerAssignmentR")

library(SigProfilerAssignmentR)
library(ggplot2)
library(RColorBrewer)
library(tidyverse)
```


#First, to CNA signatures
```{r}


acts_ed <- read.csv("~/pdx_la_sanger/results/paper_pdx_plataforma_associacoes/COSMIC_CNV48_activities_editedw2_fev_25.csv", header = TRUE)

# Transformar a coluna 'Samples' em um fator com a ordem desejada
sample_order <- c("PD53355c", "PD53333f", "PD53330c", "PD53337a", "PD53363a", "PD53346a", "PD53369a", "PD53352d", "PD53343h", "PD53338a", "PD53368a", "PD53351a", "PD53350d", "PD53347c", "PD53348a", "PD53359c", "PD53357c", "PD53362a", "PD53367a", "PD53345a", "PD53364c", "PD53349d", "PD53361a", "PD53354a", "PD53334a", "PD53332d", "PD53358a", "PD53366a", "PD53331a", "PD53339a", "PD53341a", "PD53342a", "PD53353a", "PD53365a")

acts_ed$Samples <- factor(acts_ed$Samples, levels = sample_order)

acts_ed <- na.omit(acts_ed)
# Verificar se a ordem está correta
levels(acts_ed$Samples)

#mudando a forma da tabela
acts_tidy = acts_ed %>%
    pivot_longer(cols = !Samples,
                 names_to = 'Signature',
                 values_to = 'Mutations')
```


```{r}
# Generate stacked barplot (percent stacked)
library(tidyr)
library(dplyr)
library(ggplot2)
library(ggsci)



# Criar paleta de cores personalizada
npg_colors <- pal_npg("nrc")(10)  # Cores NPG
extra_colors <- c("#FF7F00", "#6A3D9A", "#A6CEE3", "#1F78B4", "#B2DF8A", "#33A02C")
my_palette <- c(npg_colors, extra_colors)  # Total de 16 cores


plot1 <- ggplot(acts_tidy) +
    aes(x = Samples, y = Mutations, fill = Signature) +
    geom_bar(position='stack', stat = 'identity') +
    theme_classic() +
    labs(x = "Samples", y = "CNA Signatures Contribution (Absolute)") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    scale_fill_manual(values = my_palette)


plot1 + coord_cartesian(xlim = c( 0,35), ylim = c( 0,400), expand = FALSE)
#####

library(tidyr)
library(dplyr)
library(ggplot2)
library(ggsci)

# Criar paleta de cores personalizada
npg_colors <- pal_npg("nrc")(10)  # Cores NPG
extra_colors <- c("#FF7F33", "#6A3D9A", "#A6CEE3", "#1F78B4", "#B2DF8A", "#33A02C")

# Definir um vetor de cores para as assinaturas
my_palette <- c(npg_colors, extra_colors)

# Adicionar a cor cinza claro para o grupo "hjjlojn"
signature_levels <- unique(acts_tidy$Signature)
custom_palette <- setNames(my_palette[1:length(signature_levels)], signature_levels)
custom_palette["empty"] <- "#D3D3D3"  # Cinza claro

# Criar o gráfico
plot2 <- ggplot(acts_tidy, aes(x = Samples, y = Mutations, fill = Signature)) +
    geom_bar(position = 'fill', stat = 'identity') +
    theme_classic() +
    labs(x = "Samples", y = "CNA Signatures Contribution (Relative)") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    scale_fill_manual(values = custom_palette) 

# Ajustar e exibir o gráfico
plot2 + coord_cartesian(xlim = c(0, 35), expand = FALSE)



```


```{r}
# Calculate number of CNA per sample
number_of_CNA = rowSums(acts[,-1])

# Selecting the activities of only the top 10 mutated cases
top_10_CNA_samples = acts[order(number_of_CNA,
                                    decreasing = T)[1:10],]

# Reformatting and plotting
top_10_CNA_samples %>%
  pivot_longer(cols = !Samples,
               names_to = 'Signature',
               values_to = 'CNA_alterations') %>%
  ggplot() +
  aes(x = reorder(Samples, CNA_alterations), y = CNA_alterations, fill = Signature) +
  geom_bar(position = 'stack', stat = 'identity') +
   theme_classic() +
    labs(x = "Samples", y = " Top_10 samples with CNA Signatures")+
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    scale_fill_manual(values = my_palette)

# Selecting the activities of only the top 10 mutated cases
FCS_tumor <-  variant_counts_cna_score_table$FCS_tumor
top_10 = variant_counts_cna_score_table[order(FCS_tumor,
                                    decreasing = T)[1:10],]


```


#Second to mutational signatures
```{r}

#loading the tables
d  <- read.table("/scr/anniecristh/pdx_la_sanger/results/mutational_signatures/COSMIC_SBS96_Activities.txt", header=TRUE)

Table_metadata_07_10_24v2 <- read.csv("/data04/projects04/PatriciaPossik/pdx_la_sanger/results/Associations_Regressions/Table_metadata_07_10_24v2.csv")


mut_sig <- d

# Rename column
#mut_sig <- mut_sig %>% 
  #rename(Tumor_Sample_Barcode = Samples)

# Transformar a coluna 'Samples' em um fator com a ordem desejada
sample_order <- c("PD53355c", "PD53333f", "PD53330c", "PD53337a", "PD53363a", "PD53346a", "PD53369a", "PD53352d", "PD53343h", "PD53338a", "PD53368a", "PD53351a", "PD53350d", "PD53347c", "PD53348a", "PD53359c", "PD53357c", "PD53362a", "PD53367a", "PD53345a", "PD53364c", "PD53349d", "PD53361a", "PD53354a", "PD53334a", "PD53332d", "PD53358a", "PD53366a", "PD53331a", "PD53339a", "PD53341a", "PD53342a", "PD53353a", "PD53365a")

mut_sig$Samples <- factor(mut_sig$Samples, levels = sample_order)

mut_sig <- na.omit(mut_sig)
# Verificar se a ordem está correta
levels(mut_sig$Samples)

#mudando a forma da tabela
acts_tidy_mut = mut_sig %>%
    pivot_longer(cols = !Samples,
                 names_to = 'Signature',
                 values_to = 'Mutations')


library(ggsci)
library(colorspace)
library(scales)

# Obter a paleta original
npg_colors <- pal_npg("nrc")(10)

# Clarear as cores (ajuste do fator de clareamento conforme necessário)
lighter_npg_colors <- lighten(npg_colors, amount = 0.35)# 30% mais claro

# Exibir as cores originais e as clareadas
show_col(c(npg_colors, lighter_npg_colors))

# Adicionar a cor cinza claro para o grupo "hjjlojn"
signature_levels <- unique(acts_tidy_mut$Signature)
custom_palette <- setNames(my_palette[1:length(signature_levels)], signature_levels)
custom_palette["empty"] <- "#D3D3D3"  # Cinza claro


plot1 <- ggplot(acts_tidy_mut) +
    aes(x = Samples, y = Mutations, fill = Signature) +
    geom_bar(position='stack', stat = 'identity') +
    theme_classic() +
    labs(x = "Samples", y = " Mutational Signatures Contribution")+
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    scale_fill_manual(values = selected_colors) 


plot1 + coord_cartesian(xlim = c( 0,35), ylim = c( 0,200), expand = FALSE)


plot2 <- ggplot(acts_tidy_mut) +
    aes(x = Samples, y = Mutations, fill = Signature) +
    geom_bar(position='fill', stat = 'identity') +
    theme_classic() +
    labs(x = "Samples", y = " Relative Mutational Signatures Contribution")+
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    scale_fill_manual(values = lighter_npg_colors) 


plot2 + coord_cartesian(xlim = c( 0,35), expand = FALSE)


# Calculate number of mutations per sample
number_of_mutations = rowSums(acts[,-1])

# Selecting the activities of only the top 10 mutated cases
top_10_mutated_samples = acts[order(number_of_mutations,
                                    decreasing = T)[1:10],]

# Reformatting and plotting
top_10_mutated_samples %>%
  pivot_longer(cols = !Samples,
               names_to = 'Signature',
               values_to = 'Mutations') %>%
  ggplot() +
  aes(x = reorder(Samples, Mutations), y = Mutations, fill = Signature) +
  geom_bar(position = 'fill', stat = 'identity') +
   theme_classic() +
    labs(x = "Samples", y = " CNA Signatures Contribution (%)")+
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    scale_fill_manual(values = my_palette)

```


```{r}
#loading the tables
d  <- read.table("/scr/anniecristh/pdx_la_sanger/results/mutational_signatures/COSMIC_SBS96_Activities.txt", header=TRUE)

Table_metadata <- read.csv("/data04/projects04/PatriciaPossik/pdx_la_sanger/results/Associations_Regressions/Table_metadata_20_02_25.csv")


mut_sig <- d

# Rename column
mut_sig <- mut_sig %>% 
  rename(Tumor_Sample_Barcode = Samples)

#merging tables

Sig_table <- merge(mut_sig, Table_metadata, by = "Tumor_Sample_Barcode")


Sig_table <- cbind(Sig_table$Tumor_Sample_Barcode, Sig_table$Anatomic_Site, Sig_table$Stage_primary, Sig_table$Clinical_Stage_new, Sig_table$SBS7a, Sig_table$SBS7b, Sig_table$SBS1, Sig_table$SBS5, Sig_table$SBS38) 
Sig_table <- as.data.frame(Sig_table)
colnames(Sig_table) <- c('Tumor_Sample_Barcode', 'Anatomic_Site', 'Stage_primary','Clinical_Stage_new', 'SBS7a', 'SBS7b', 'SBS1', 'SBS5', 'SBS38')

str(Sig_table)
Sig_table$SBS7a <- as.numeric(Sig_table$SBS7a)
Sig_table$SBS7b<- as.numeric(Sig_table$SBS7b)
Sig_table$SBS1 <- as.numeric(Sig_table$SBS1)
Sig_table$SBS5 <- as.numeric(Sig_table$SBS5)
Sig_table$SBS38 <- as.numeric(Sig_table$SBS38)
# Somar as duas colunas referente as assinaturas de UV e armazenar o resultado em uma nova coluna
Sig_table$soma_UV <- Sig_table$SBS7a + Sig_table$SBS7b

# Calcular a soma de cada linha para as quatro colunas
row_sums <- rowSums(Sig_table[, c('soma_UV', 'SBS1', 'SBS5', 'SBS38')])

# Dividir cada coluna pela soma da linha correspondente para obter valores relativos
Sig_table$soma_UV_rel <- Sig_table$soma_UV / row_sums
Sig_table$SBS1_rel <- Sig_table$SBS1 / row_sums
Sig_table$SBS5_rel <- Sig_table$SBS5 / row_sums
Sig_table$SBS38_rel <- Sig_table$SBS38/ row_sums


colnames(Sig_table) <- trimws(colnames(Sig_table)) 

write.csv(Sig_table, "Sig_table.csv", row.names=TRUE)





Sig_table_gather <- gather(Sig_table, key="UV_sig", value="value", 3:4)





```

```{r}
```


```{r}
p1 <- ggplot(Sig_table_gather, aes(x =value, y=soma_UV) +
  geom_bar(position = "stack") +
  labs(x = "Stage", 
       y = "UV-sig", 
       fill = "Signature") +
  scale_fill_manual(values = c("SBS7a" = "#4DBBD5B2", "SBS7b" = "#8491B4B2"),
                    labels = c("SBS7a", "SBS7b")) + theme_classic()
p1



plot1 <- ggplot(Sig_table_gather) +
    aes(x = Clinical_Stage_new, y = value, fill = UV_sig) +
    geom_bar(position='fill', stat = 'identity') +
    theme_classic() +
    labs(x = "Stage", y = " UV-signatures")+
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    scale_fill_manual(values = selected_colors)+
   scale_y_continuous(labels = scales::percent)

plot1



# Remover NAs
Sig_table_clean <- Sig_table %>%
 dplyr::filter(!is.na(Stage_primary))

library(ggplot2)
library(ggsci) 
library(ggpubr)# Para usar scale_fill_npg()

p <- ggplot(Sig_table_clean, aes(x = Stage_primary, y = soma_UV_rel, fill = Stage_primary)) +
    geom_boxplot(outlier.shape = NA, color = "black") +
    geom_jitter(color = "darkgray", width = 0.2, alpha = 0.6, size = 2) +  # Jittered points
    scale_fill_npg() +  # Apply NPG palette for filling
    labs(x = "Tumour Stage", 
         y = "UV_signature proportion") +
    stat_compare_means(method = "wilcox.test", label = "p.format", 
                       comparisons = list(c("early", "late"))) +
    theme_classic()  # Correct placement of theme_classic

# Display the plot
print(p)
 
shapiro.test(Sig_table_clean$soma_UV_rel)

#Mann-Whitney - Wilcoxon Rank Sum - Unpaired data
wilcox.test(Sig_table_clean$soma_UV_rel~Sig_table_clean$Stage_primary) #not normal data

#####################
p <- ggplot(Sig_table_clean, aes(x = Clinical_Stage_new, y = soma_UV_rel, fill = Clinical_Stage_new)) +
    geom_boxplot(outlier.shape = NA, color = "black") +
    geom_jitter(color = "darkgray", width = 0.2, alpha = 0.6, size = 2) +  # Jittered points
    scale_fill_npg() +  # Apply NPG palette for filling
    labs(x = "Tumour Stage", 
         y = "UV_signature proportion") +
    stat_compare_means(method = "kruskal.test", label = "p.format") +
    theme_classic()  # Correct placement of theme_classic

# Display the plot
print(p)

Sig_table_clean$Clinical_Stage_new

# Filtrar linhas onde Clinical_Stage_new é 'I' ou 'II'
Sig_table_clean_filtered <- Sig_table_clean %>%
  filter(Clinical_Stage_new %in% c('II', 'III'))


print(Sig_table_clean_filtered)


p <- ggplot(Sig_table_clean_filtered, aes(x = Clinical_Stage_new, y = soma_UV_rel, fill = Clinical_Stage_new)) +
    geom_boxplot(outlier.shape = NA, color = "black") +
    geom_jitter(color = "darkgray", width = 0.2, alpha = 0.6, size = 2) +  # Jittered points
    scale_fill_npg() +  # Apply NPG palette for filling
    labs(x = "Tumour Stage", 
         y = "UV_signature proportion") +
    stat_compare_means(method = "wilcox.test", label = "p.format") +
    theme_classic()  # Correct placement of theme_classic

# Display the plot
print(p)

```


```{r}
# Carregar pacotes necessários
library(ggplot2)
library(ggpubr)  # Para adicionar o teste estatístico
library(ggsci)   # Para a paleta de cores NPG

shapiro.test(Sig_table_clean$soma_UV)
kruskal.test(soma_UV ~ Clinical_Stage_new, data = Sig_table_clean)
# Instalar e carregar o pacote FSA, se ainda não tiver
install.packages("FSA")  # Apenas se não tiver o pacote instalado
library(FSA)
Sig_table$Clinical_Stage_new <- as.factor(Sig_table_clean$Clinical_Stage_new)

# Executar o teste de Dunn com correção de Bonferroni
p <- dunnTest(soma_UV ~ Clinical_Stage_new, data = Sig_table_clean, method = "bonferroni")
print(p)
p$res
print(p$res)
# Criar um data frame com os resultados do teste de Dunn
dunn_results <- as.data.frame(p$res)
write.csv(dunn_results, "dunn_test_results_UV_sig_stage.csv", row.names = FALSE)


# Criando o boxplot com o estilo desejado
ggplot(Sig_table_clean, aes(x = Clinical_Stage_new, y = soma_UV, fill = Clinical_Stage_new)) +
  geom_boxplot(width = 0.6, outlier.shape = 1, outlier.size = 1.6, outlier.alpha = 0, 
               position = position_dodge(width = 0.75)) +
  geom_jitter(alpha = 0.5, color = "black", width = 0.2) +  # Adiciona pontos individuais
  stat_summary(fun = "median", geom = "point", shape = 23, size = 4, fill = "gray") +  # Destaca a mediana
  labs(x = "Stage", y = "UV Signature (SBS7a + SBS7b)") +
  scale_fill_npg() +  # Aplicando a paleta NPG do ggsci
  stat_compare_means(aes(group = Clinical_Stage_new), method = "kruskal.test", 
                     label.y = max(Sig_table_clean$soma_UV) * 1.05) +  # Teste de Kruskal-Wallis
  theme_classic()

kruskal.test(soma_UV ~ Clinical_Stage_new, data = Sig_table_clean)

#early vs late

wilcox.test(soma_UV ~ Stage_primary, data = Sig_table_clean)
p3<- ggplot(Sig_table_clean, aes(x = Stage_primary, y = soma_UV, fill = Stage_primary)) +
  geom_boxplot(width = 0.6, outlier.shape = 1, outlier.size = 1.6, outlier.alpha = 0, 
               position = position_dodge(width = 0.75)) +
  geom_jitter(alpha = 0.5, color = "black", width = 0.2) +  # Adiciona pontos individuais
  stat_summary(fun = "median", geom = "point", shape = 23, size = 4, fill = "gray") +  # Destaca a mediana
  labs(x = "Stage", y = "UV Signature (SBS7a + SBS7b)") +
  scale_fill_npg() +  # Aplicando a paleta NPG do ggsci
  stat_compare_means(aes(group = Stage_primary), method = "wilcox", 
                     label.y = max(Sig_table_clean$soma_UV) * 1.05) +  # Teste de Kruskal-Wallis
  theme_classic()
p3


# anatomic site

kruskal.test(soma_UV ~ Anatomic_Site, data = Sig_table_clean)

p4<- ggplot(Sig_table_clean, aes(x = Anatomic_Site, y = soma_UV, fill = Anatomic_Site)) +
  geom_boxplot(width = 0.6, outlier.shape = 1, outlier.size = 1.6, outlier.alpha = 0, 
               position = position_dodge(width = 0.75)) +
  geom_jitter(alpha = 0.5, color = "black", width = 0.2) +  # Adiciona pontos individuais
  stat_summary(fun = "median", geom = "point", shape = 23, size = 4, fill = "gray") +  # Destaca a mediana
  labs(x = "Anatomic site", y = "UV Signature (SBS7a + SBS7b)") +
  scale_fill_npg() +  # Aplicando a paleta NPG do ggsci
  stat_compare_means(aes(group = Anatomic_Site), method = "wilcox", 
                     label.y = max(Sig_table_clean$soma_UV) * 1.05) +  # Teste de Kruskal-Wallis
  theme_classic()
p4

```


